name: Galactifun
author: Slimefun Addon Community
description: Space addon for Slimefun
main: io.github.seggan.galactifun.Galactifun
version: ${project.version}
api-version: 1.14
depend:
- Slimefun

commands:
  ptp:
    description: Teleport to a planet
    permission: galactifun.ptp

permissions:
  galactifun.ptp:
    description: The permission for the /ptp command
    default: op