name: Galactifun
authors: [Seggan, Mooy1] # add ur names
description: Space addon for Slimefun
main: io.github.seggan.galactifun.Galactifun # could change package name to io.github.slimefun-addon-community?
version: ${project.version}
api-version: 1.16
depend:
- Slimefun

commands:
  ptp:
    description: Teleport to a planet
    permission: galactifun.ptp

permissions:
  galactifun.ptp:
    description: The permission for the /ptp command
    default: op